sudo: false
language: python
python:
  - "3.5"

env:
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=packaging
  - TOXENV=style
  - TOXENV=docs

install:
  - pip install tox codecov

script:
  - travis_wait tox

after_success:
  - tox -e coverage-report
  - codecov
